version: '3.8'

volumes:
  db_dev:

services:
  db_dev:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - db_dev:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres