# PostgreSQL. Versions 9.3 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On macOS with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On macOS with MacPorts:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem 'pg'
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  primary:
    <<: *default
    database: multiple_db_development
    username: <%= ENV.fetch('MULTIPLE_DB_DATABASE_USERNAME') %>
    password: <%= ENV.fetch('MULTIPLE_DB_DATABASE_PASSWORD') %>
    host: <%= ENV.fetch('MULTIPLE_DB_DATABASE_HOST') %>
  primary_replica:
    <<: *default
    database: multiple_db_development
    username: <%= ENV['MULTIPLE_DB_DATABASE_USERNAME'] %>
    password: <%= ENV['MULTIPLE_DB_DATABASE_PASSWORD'] %>
    host: <%= ENV['MULTIPLE_DB_DATABASE_HOST'] %>
    replica: true

test:
  <<: *default
  username: <%= ENV.fetch('MULTIPLE_DB_DATABASE_USERNAME') %>
  password: <%= ENV.fetch('MULTIPLE_DB_DATABASE_PASSWORD') %>
  host: <%= ENV.fetch('MULTIPLE_DB_DATABASE_HOST') %>
  database: multiple_db_test

production:
  primary:
    <<: *default
    database: multiple_db_production
    username: <%= ENV.fetch('MULTIPLE_DB_DATABASE_USERNAME') %>
    password: <%= ENV.fetch('MULTIPLE_DB_DATABASE_PASSWORD') %>
    host: <%= ENV.fetch('MULTIPLE_DB_DATABASE_HOST') %>
  primary_replica:
    <<: *default
    database: multiple_db_production
    username: <%= ENV.fetch('MULTIPLE_DB_DATABASE_USERNAME') %>
    password: <%= ENV.fetch('MULTIPLE_DB_DATABASE_PASSWORD') %>
    host: <%= ENV.fetch('MULTIPLE_DB_REPLICA_HOST') %>
    replica: true
